services:
    marttiphpbb.emailonlypasswordreset.listener:
        class: marttiphpbb\emailonlypasswordreset\event\listener
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }

    marttiphpbb.emailonlypasswordreset.console.info:
        class: marttiphpbb\emailonlypasswordreset\console\info
        arguments:   
            - '@user'
            - '@dbal.conn'
        tags:
            - { name: console.command }            