services:
    marttiphpbb.emailonlypasswordreset.listener:
        class: marttiphpbb\emailonlypasswordreset\event\listener
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    marttiphpbb.emailonlypasswordreset.console.info:
        class: marttiphpbb\emailonlypasswordreset\console\info
        arguments:   
            - '@user'
            - '@dbal.conn'
        tags:
            - { name: console.command }            